// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AppPlayground",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "AppPlayground",
            targets: ["AppModule"],
            bundleIdentifier: "com.codewithnathan.AppPlayground",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .paper),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/magickworx/StarRatingViewSwiftUI", "1.1.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "StarRatingViewSwiftUI", package: "starratingviewswiftui")
            ],
            path: "."
        )
    ]
)